// ============================================================
// THE DARKROOM — commissioning a CONTACT SHEET for any idea
// (independent of the Stage gate).
// ============================================================
// Latency is choreography: the team commissions from the idea card,
// the card takes the IN THE DARKROOM stamp, and the sheet develops
// in its own time (20–30s) before landing as THREE frames
// (print_options). The team then chooses the select — the chosen
// frame becomes print_url, the idea's hanging print — and the sheet
// is kept, so a different frame can be chosen later on taste alone,
// with no darkroom wait. The wait is the point — a sheet is
// developed, not fetched; the choice is the team's, not the model's.
//
// TWO MODES, ONE CHOREOGRAPHY. Which one runs is decided by the
// deployment, not by a flag anyone sets: commissionPrint always asks
// app/api/darkroom for a sheet, and that route answers 503 when no
// image model is configured. The answer is remembered for the session.
//
//   LIVE — the route renders three frames in parallel from the
//   engagement's standing art direction (IMAGE_ART_DIRECTION in
//   config) plus the idea's words plus the team's note. The model's
//   own latency IS the beat; nothing is padded to reach the staged
//   20–30s. A live failure returns the row to null so the card can be
//   re-commissioned at once — it NEVER falls back to the stand-ins,
//   because substituting house art for a render the room asked for is
//   a lie the room cannot detect.
//
//   SHOWCASE — no key, so the develop time is a staged 20–30s and the
//   sheet is three of eight pre-rendered duotone compositions
//   (public/prints/, generated by scripts/generate-prints.py), never
//   repeating the idea's current print.
//
// In both modes state persists through the supabase shim, so
// BroadcastChannel realtime carries the stamp and the reveal to every
// open tab. The develop lives in the commissioning tab — if that tab
// closes mid-develop the sheet stays in the darkroom until the
// ceiling releases it (acceptable here; a real queue would not have
// this property — see the reaper note below).
//
// FORMAT LAW (docs/ogilvy-showcase-direction.md, Round 9): the
// canonical print is a CINEMATIC 16:9 KEY VISUAL (the showcase
// stand-ins render at 1600×900), and no surface ever crops one —
// every mount is a true 16:9 box. A real image model MUST generate
// at 16:9 (1600×900 or larger), and the art-direction prompt should
// ask for a "cinematic campaign key visual" composed for the wide
// frame — never square or portrait renders that a surface would
// have to crop or letterbox unpredictably.
//
// THE NOTE TO THE DARKROOM: every commission may carry an OPTIONAL
// free-text note from the team ("Warmer. Put people in it." / "Night,
// city, wet streets."), captured in the note modal before the develop
// starts and stored on ideas.print_note. Skipping is one click — the
// note is never required, and a commission sent without one clears
// any note the previous commission left.
//
// STILL OWED, BEFORE A REAL ROOM RUNS ON THIS (dev team):
//   1. STORAGE. The route returns frames as data URLs, which the
//      in-memory shim holds happily and which is what makes a
//      keys-only demo deploy possible with no bucket at all. Against a
//      real Postgres backend this must change — three 2K data URLs on
//      every row would bloat `ideas` badly. Upload each frame in the
//      route and return public URLs instead; every surface treats
//      print_options as opaque strings, so nothing downstream moves.
//   2. A REAPER (U6's server half): a scheduled server-side sweep
//      returning any row left `developing` past the ceiling to
//      print_status = null, because a server render can die mid-flight
//      too. The client recovery here (isPrintStalled /
//      recoverStalledPrint) stays even then — it is the participant's
//      own way out between sweeps, and the only recovery a showcase
//      deployment can run at all.
//   3. A SPEND BOUND. Nothing rate-limits commissioning, and three
//      renders land on every click. Fine behind a protected demo URL;
//      not fine on an open one.
//
// SHOWCASE LIMIT (deliberate): the stand-in prints are pre-rendered,
// so in showcase mode a note CANNOT change the art. Rather than let it
// vanish, the showcase makes the note LEGIBLE — it rides the
// developing state, the resulting contact sheet's header, and the
// chosen print as provenance (noteSlug below is the one formatter
// every surface uses). Live mode keeps all of that AND changes the
// picture, which is the one difference the room can actually see.
// ============================================================

import { useEffect, useState } from "react";
import { supabase } from "./supabase";
import { write } from "./db";
import { IMAGE_VOCAB } from "./config";
import { SHOWCASE_PRINTS, PRINT_POOL } from "./showcase-data";
import type { Idea } from "./types";

// Ideas currently developing in THIS tab (timer owner). Lets a reopened
// ExpandedCard show the darkroom state even before a refetch lands.
const developing = new Set<string>();

export function isInDarkroom(ideaId: string): boolean {
  return developing.has(ideaId);
}

// ── U6 — THE DEVELOP CEILING, AND RECOVERY ───────────────────
// The develop clock is a setTimeout in the commissioning tab, so a
// refresh, a closed tab or a failed finish write (flagged by U3's
// wrapper in the timer below) leaves the row `developing` with nothing
// anywhere that will ever clear it. The recovery is judged CLIENT-SIDE
// from data already on the row — NO NEW COLUMN: commissionPrint's own
// state write stamps `updated_at`, so the timestamp needed to judge
// staleness is already there. The obvious instinct is a
// `print_started_at` column; resist it — `updated_at` is sufficient,
// and its one distortion is CONSERVATIVE: an unrelated write (an
// autosave mid-develop) refreshes the stamp and merely delays the
// stalled verdict by one more ceiling, it can never fire it early.
//
// The ceiling is the develop's maximum plus a wide margin. The margin
// absorbs slow tabs and the modest clock skew between devices, since
// `updated_at` is stamped by whichever client wrote it (there is no
// server trigger). Round 14 stands: the 20–30s beat is the work and is
// NOT shortened to make recovery easier — the harness drives
// `updated_at` through the showcase bus instead.

// ── The render prompt ─────────────────────────────────────────
// Lives in lib/render-prompt.ts — a pure module both this file and the
// server route import, so the route never pulls React + the supabase
// shim in just to compose a string. Re-exported here because the
// darkroom is where a reader looks for it.
export { buildRenderPrompt } from "./render-prompt";

/** The SHOWCASE develop's staged maximum. Live develops are not bound
    by this — the model takes what it takes. */
export const DEVELOP_MAX_MS = 30_000;

/** Older than this while `developing` ⇒ the clock is dead.
 *
 *  Sized for the LIVE develop, not the staged one. Three parallel 2K
 *  renders can legitimately run well past the showcase's 30s beat, and
 *  the tab that owns a develop is exempt from this judgement anyway
 *  (the `developing` Set) — so the only reader this bounds is a tab
 *  WATCHING someone else's develop. Judging that neighbour dead at 45s
 *  would offer "recover" on a perfectly healthy render, and taking it
 *  would abandon a sheet that was about to land and pay for a second
 *  one. The ceiling's job is to prove a clock is dead, and with a real
 *  model attached that proof honestly takes longer. */
export const DEVELOP_CEILING_MS = 180_000;

type StallJudgeable = Pick<Idea, "id"> & {
  print_status?: string | null;
  updated_at?: string | null;
};

/** A develop that outlived its ceiling with no live timer behind it.
 *  The tab that OWNS the timer is never stalled while the timer is
 *  pending (the `developing` Set); after the timer fired — including
 *  the failure path where the finish write was refused — the Set is
 *  clear and the ceiling judges the row like any other tab would.
 *  A `developing` row with no parseable `updated_at` cannot be proven
 *  stale and stays protected — conservative, and the only honest call
 *  without a timestamp. */
export function isPrintStalled(idea: StallJudgeable): boolean {
  if (idea.print_status !== "developing") return false;
  if (developing.has(idea.id)) return false;
  const at = Date.parse(idea.updated_at ?? "");
  if (Number.isNaN(at)) return false;
  return Date.now() - at > DEVELOP_CEILING_MS;
}

/** `isPrintStalled`, kept honest over time for a card that stays
 *  mounted: a stranded row emits no event that would re-render its
 *  card, so this hook re-checks once, exactly when the ceiling passes.
 *  Cheap — one timeout per developing card, none for settled ones. */
export function useStalledDevelop(idea: StallJudgeable): boolean {
  const [, tick] = useState(0);
  const stalled = isPrintStalled(idea);
  const { id, print_status, updated_at } = idea;
  useEffect(() => {
    if (print_status !== "developing" || stalled) return;
    const at = Date.parse(updated_at ?? "");
    if (Number.isNaN(at)) return;
    const wait = Math.max(500, at + DEVELOP_CEILING_MS - Date.now() + 250);
    const t = setTimeout(() => tick((n) => n + 1), wait);
    return () => clearTimeout(t);
  }, [id, print_status, updated_at, stalled]);
  return stalled;
}

/** Deterministic sheet pick: three distinct prints from the pool,
    seeded by a stable hash of the idea id, never repeating the idea's
    CURRENT print (a new sheet must offer new frames) and avoiding the
    previous sheet where the small showcase pool allows, so a
    re-commission is visibly new. The idea's mapped showcase print
    leads the sheet when it's free — a real implementation renders
    three genuinely new images here, in parallel. */
export function sheetForIdea(
  idea: Pick<Idea, "id"> & { print_url?: string | null; print_options?: string[] | null }
): string[] {
  let h = 0;
  for (let i = 0; i < idea.id.length; i++) h = (h * 31 + idea.id.charCodeAt(i)) >>> 0;
  const taken = new Set<string>(idea.print_options ?? []);
  if (idea.print_url) taken.add(idea.print_url);
  const frames: string[] = [];
  const mapped = SHOWCASE_PRINTS[idea.id];
  if (mapped && !taken.has(mapped)) frames.push(mapped);
  const start = h % PRINT_POOL.length;
  for (let i = 0; i < PRINT_POOL.length && frames.length < 3; i++) {
    const c = PRINT_POOL[(start + i) % PRINT_POOL.length];
    if (!frames.includes(c) && !taken.has(c)) frames.push(c);
  }
  // Small-pool fallback: relax the previous-sheet exclusion — but never
  // re-offer the print currently hanging.
  for (let i = 0; i < PRINT_POOL.length && frames.length < 3; i++) {
    const c = PRINT_POOL[(start + i) % PRINT_POOL.length];
    if (!frames.includes(c) && c !== idea.print_url) frames.push(c);
  }
  return frames;
}

// ── Print provenance ─────────────────────────────────────────
// A print is generated FROM a draft; the draft keeps moving. The
// snapshot below (stored on ideas.print_source at commission time)
// lets every surface know which draft the hanging print came from.
//
// DEV TEAM: the real implementation should also keep PRINT HISTORY
// server-side (a print_runs table: idea_id, source snapshot, url,
// commissioned_at) rather than only the latest print_source — the
// Edition may later want to show the first-draft print beside the
// final one. The showcase keeps just the latest snapshot.

/** The snapshot format: name and description joined by one newline. */
export function printSourceOf(idea: Pick<Idea, "name" | "description">): string {
  return `${idea.name ?? ""}\n${idea.description ?? ""}`;
}

// ── The note's slug ──────────────────────────────────────────
// The note prints as a Courier production slug wherever it appears —
// `NOTE · Warmer. Put people in it.` — so it reads as a mark of what
// was asked for, in the same voice as every other true-data slug in
// the system. ONE formatter, so the developing state, the sheet
// header, and the print's provenance chip never disagree. The slug's
// prefix is vocabulary (IMAGE_VOCAB.noteSlugLabel — NOTE in the
// editorial skin, DIRECTION in the base register), not a mechanic.

/** Format a note as its slug, truncated gracefully at `max` characters
    (word boundary where one is near enough, trailing punctuation
    dropped before the ellipsis). Returns null for a missing or blank
    note, so call sites read `{slug && …}`. Notes are single-line here
    even when typed across several: a slug is one line of data. */
export function noteSlug(note: string | null | undefined, max = 64): string | null {
  const t = (note ?? "").trim().replace(/\s+/g, " ");
  if (!t) return null;
  const label = IMAGE_VOCAB.noteSlugLabel;
  if (t.length <= max) return `${label} · ${t}`;
  const cut = t.slice(0, max);
  const sp = cut.lastIndexOf(" ");
  const body = (sp > max * 0.6 ? cut.slice(0, sp) : cut).replace(/[\s.,;:!?—–-]+$/, "");
  return `${label} · ${body}…`;
}

const norm = (s: string) => s.trim().replace(/\s+/g, " ").toLowerCase();

/** Char-level edit distance — two-row DP; inputs are short (a name +
    a few sentences), so the quadratic cost is nothing. */
function editDistance(a: string, b: string): number {
  if (a === b) return 0;
  let prev = Array.from({ length: b.length + 1 }, (_, i) => i);
  for (let i = 1; i <= a.length; i++) {
    const row = [i];
    for (let j = 1; j <= b.length; j++) {
      row[j] = Math.min(
        prev[j] + 1,
        row[j - 1] + 1,
        prev[j - 1] + (a[i - 1] === b[j - 1] ? 0 : 1)
      );
    }
    prev = row;
  }
  return prev[b.length];
}

/** True when the idea's current text has meaningfully diverged from the
    draft its developed print was commissioned from: a changed name, or
    >15% char-level drift in the description (whitespace/case ignored).
    Never true while a print is developing, or for prints with no
    recorded source (pre-provenance prints stay unmarked). */
export function isPrintStale(
  idea: Pick<Idea, "name" | "description" | "print_status" | "print_url" | "print_source">
): boolean {
  if (idea.print_status !== "developed" || !idea.print_url || !idea.print_source) return false;
  const nl = idea.print_source.indexOf("\n");
  const srcName = nl === -1 ? idea.print_source : idea.print_source.slice(0, nl);
  const srcDesc = nl === -1 ? "" : idea.print_source.slice(nl + 1);
  if (norm(idea.name ?? "") !== norm(srcName)) return true;
  const a = norm(srcDesc);
  const b = norm(idea.description ?? "");
  if (a === b) return false;
  const longest = Math.max(a.length, b.length, 1);
  return editDistance(a, b) / longest > 0.15;
}

/** Commission a contact sheet. Stamps the idea IN THE DARKROOM
    immediately; the developed sheet — three frames, no chosen print —
    lands after the staged develop time. Works for first sheets AND
    deliberate re-pictures ("Picture it again" on a stale print, "New
    sheet" on a chosen one) — the only thing it refuses is a develop
    already in flight. Regeneration is never automatic: an edit marks
    the print stale, and only a click here re-commissions it.

    `note` is the team's OPTIONAL note to the darkroom, sent from the
    note modal. A real implementation appends it to the engagement's
    art-direction prompt (see REAL IMPLEMENTATION PLUG-IN, step 1); the
    showcase can only make it legible. Blank or omitted CLEARS the
    column — a fresh commission with nothing to say must not inherit
    the last commission's direction as false provenance.

    TWO WRITES, NOT ONE (R7). The text and the print state used to ride
    in a single statement, so a print column the deployment could not
    accept ALSO discarded the participant's edits — the audit's single
    worst consequence of defect #1. They are now separate statements in
    a fixed order: the words first, the picture request second. A
    failed commission can never cost an idea its words, and the caller
    is told which of the two failed so the card can say the right
    thing. */
export type CommissionResult =
  | { ok: true }
  | { ok: false; stage: "text" | "print"; message: string };

export async function commissionPrint(
  idea: Pick<Idea, "id" | "name" | "description" | "print_status"> & {
    print_url?: string | null;
    print_options?: string[] | null;
    updated_at?: string | null;
  },
  note?: string | null
): Promise<CommissionResult> {
  // The guard narrowed for U6: a develop in flight in THIS tab, or a
  // `developing` row still inside the ceiling, is refused as before —
  // but a row PAST the ceiling has no clock behind it, and refusing it
  // was what made a stranded idea permanently unpicturable.
  if (developing.has(idea.id)) return { ok: true };
  if (idea.print_status === "developing" && !isPrintStalled(idea)) return { ok: true };
  developing.add(idea.id);

  // 1 — THE WORDS. Snapshot the draft this sheet is being generated
  // from. Commissioning is an explicit act on the draft as displayed,
  // and without saving it a sheet commissioned over unsaved edits
  // develops into an instant — and false — FROM AN EARLIER DRAFT (the
  // row would still carry the old text while print_source carries the
  // new). This statement carries nothing the darkroom owns, so it
  // cannot be rejected for a print column that does not exist.
  const text = await write(
    "ideas.update:commission-text",
    supabase
      .from("ideas")
      .update({
        name: idea.name,
        description: idea.description,
        updated_at: new Date().toISOString(),
      })
      .eq("id", idea.id)
  );
  if (!text.ok) {
    developing.delete(idea.id);
    return { ok: false, stage: "text", message: text.message };
  }

  // 2 — THE PICTURE REQUEST. Only now, and only its own columns. If
  // this fails the words above are already on the row; the card says
  // the darkroom did not take the commission and nothing typed is lost.
  const state = await write(
    "ideas.update:commission-print",
    supabase
      .from("ideas")
      .update({
        print_status: "developing",
        print_source: printSourceOf(idea),
        // The note lands with the stamp, not with the sheet — the room
        // should see what was asked for while the develop runs, and a
        // tab that closes mid-develop still leaves the ask on record.
        print_note: note?.trim() || null,
        updated_at: new Date().toISOString(),
      })
      .eq("id", idea.id)
  );
  if (!state.ok) {
    developing.delete(idea.id);
    return { ok: false, stage: "print", message: state.message };
  }

  // The develop runs detached: the commission is accepted here, and
  // the sheet lands on the row whenever it lands. Every surface is
  // already listening for that row update, so nothing awaits this.
  void develop(idea, note);

  return { ok: true };
}

/** Whether this deployment has a live darkroom, learned from the first
 *  commission's answer and then remembered. `null` = not yet asked.
 *  Without this, a showcase deployment pays a pointless round-trip on
 *  every single commission. */
let liveDarkroom: boolean | null = null;

/** Ask the route for a sheet. Returns the frames, or `null` when the
 *  deployment has no image model attached (503) — the one case that is
 *  NOT a failure, because it means showcase mode. Any other bad answer
 *  throws, because a configured darkroom that failed must be reported
 *  as a failure and never quietly dressed in stand-in art the room
 *  would read as real. */
async function requestSheet(
  idea: Pick<Idea, "name"> & { description?: string | null },
  note?: string | null
): Promise<string[] | null> {
  if (liveDarkroom === false) return null;

  const res = await fetch("/api/darkroom", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ name: idea.name, description: idea.description, note }),
  });

  if (res.status === 503) {
    liveDarkroom = false;
    return null;
  }
  if (!res.ok) {
    const detail = await res.json().catch(() => null);
    throw new Error(detail?.error ?? `Darkroom refused the commission (${res.status}).`);
  }

  const data = (await res.json()) as { frames?: unknown };
  const frames = Array.isArray(data.frames)
    ? data.frames.filter((f): f is string => typeof f === "string" && f.length > 0)
    : [];
  if (frames.length === 0) throw new Error("The darkroom returned an empty sheet.");

  liveDarkroom = true;
  return frames;
}

/** The develop itself, in whichever mode this deployment is in.
 *
 *  LIVE: the model's own latency IS the beat — nothing is padded to
 *  reach the staged 20–30s, per the standing ruling that the beat is
 *  the work and time is never added to natural latency.
 *
 *  SHOWCASE: there is nothing real to wait for, so the beat is staged
 *  at 20–30s and the frames are the pre-rendered stand-ins.
 *
 *  A LIVE FAILURE IS A FAILURE. It returns the row to `null` so the
 *  card offers the commission again immediately, rather than leaving
 *  it stamped and waiting on the stall ceiling. What it must never do
 *  is fall back to stand-ins: substituting abstract house art for a
 *  render the room asked for is a lie the room cannot detect. */
async function develop(
  idea: Pick<Idea, "id" | "name" | "description">,
  note?: string | null
): Promise<void> {
  const startedAt = Date.now();
  let frames: string[];

  try {
    const live = await requestSheet(idea, note);
    if (live) {
      frames = live;
    } else {
      // The staged beat, less whatever the 503 probe already spent.
      const staged = 20000 + Math.random() * (DEVELOP_MAX_MS - 20000);
      const remaining = staged - (Date.now() - startedAt);
      if (remaining > 0) await new Promise((r) => setTimeout(r, remaining));
      frames = sheetForIdea(idea);
    }
  } catch (error) {
    console.error("Darkroom develop failed:", error);
    developing.delete(idea.id);
    await write(
      "ideas.update:develop-failed",
      supabase
        .from("ideas")
        .update({ print_status: null, updated_at: new Date().toISOString() })
        .eq("id", idea.id)
    );
    return;
  }

  developing.delete(idea.id);
  // No surface is guaranteed to be open when this lands, so it reports
  // to the console and leaves the row as it found it. A row stranded
  // `developing` by this failure is U6's recovery, not this unit's —
  // recorded here so the next reader does not think the stranding was
  // handled.
  await write(
    "ideas.update:develop",
    supabase
      .from("ideas")
      .update({
        print_status: "developed",
        print_options: frames,
        // The sheet awaits its choice — no frame hangs until the team
        // picks one. Surfaces that show print_url simply wait.
        print_url: null,
        updated_at: new Date().toISOString(),
      })
      .eq("id", idea.id)
  );
}

/** U6 — recover a STALLED develop with one click. Two acts, in order:
 *  the abandon is written first (`print_status` back to null), so the
 *  give-up is explicit and on the row rather than inferred, and only
 *  then does a clean commission run. If the abandon write is refused
 *  the stamp stays and the caller reports it (U3's wrapper) — a stall
 *  the store won't release must not be dressed as a fresh develop.
 *
 *  The commission re-sends the STRANDED COMMISSION'S OWN NOTE by
 *  default — this is the same ask tried again, not a new commission
 *  with nothing to say, so the recorded direction must not be cleared
 *  by the retry. Nothing here touches `name` or `description` beyond
 *  what every commission does: persist the draft as displayed. */
export async function recoverStalledPrint(
  idea: Pick<Idea, "id" | "name" | "description" | "print_status"> & {
    print_url?: string | null;
    print_options?: string[] | null;
    print_note?: string | null;
    updated_at?: string | null;
  },
  note?: string | null
): Promise<CommissionResult> {
  const abandon = await write(
    "ideas.update:abandon-stalled-develop",
    supabase
      .from("ideas")
      .update({ print_status: null, updated_at: new Date().toISOString() })
      .eq("id", idea.id)
  );
  if (!abandon.ok) return { ok: false, stage: "print", message: abandon.message };
  return commissionPrint(
    { ...idea, print_status: null },
    note !== undefined ? note : idea.print_note ?? null
  );
}

/** Choose the select — commit one frame of the developed sheet as the
    idea's hanging print. Pure taste, no darkroom clock: print_source
    stays untouched (every frame on the sheet came from the same
    commissioned draft) and the sheet stays in print_options so the
    team can re-choose later. Returns whether the choice took, so the
    card can put the previous frame back rather than showing a choice
    the row never accepted. */
export async function chooseFrame(ideaId: string, url: string): Promise<boolean> {
  const r = await write(
    "ideas.update:choose-frame",
    supabase
      .from("ideas")
      .update({ print_url: url, updated_at: new Date().toISOString() })
      .eq("id", ideaId)
  );
  return r.ok;
}
