// ============================================================
// GENERATED FILE — DO NOT EDIT BY HAND.
// ============================================================
// Generated by scripts/build-schema-manifest.mjs from the deployment
// SQL in the STANDARD apply order (app/supabase/README.md):
/*
 *   app/supabase/schema.sql
 *   app/supabase/migrations/2026-08-04-001_present_gate_and_darkroom.sql
 *   app/supabase/migrations/2026-08-04-002_cast_vote_and_realtime.sql
 *   app/supabase/policies.sql
 */
// Regenerate with `npm run schema:build`; `npm run schema:check`
// fails the build when this file and the SQL diverge. The showcase shim
// (lib/supabase.ts) enforces everything in here, so the SQL the
// deployment team applies and the schema the showcase runs against are
// the same fact. U2 of
// docs/plans/2026-08-04-001-harden-for-live-deployment-plan.md.
// ============================================================

export type ColumnDefault =
  | { kind: "uuid" }
  | { kind: "now" }
  | { kind: "literal"; value: string | number | boolean | string[] };

export type ColumnSpec = {
  type: string;
  notNull: boolean;
  default: ColumnDefault | null;
};

/** `col in (…)`, with SQL's own null semantics: a null value passes
    the CHECK (NOT NULL is a separate law). */
export type CheckSpec = { name: string; column: string; allowed: string[] };

export type UniqueSpec = { name: string; columns: string[] };

export type ForeignKeySpec = {
  name: string;
  column: string;
  refTable: string;
  refColumn: string;
  onDelete: "cascade" | "no action";
};

export type TableSpec = {
  columns: Record<string, ColumnSpec>;
  primaryKey: string[];
  uniques: UniqueSpec[];
  checks: CheckSpec[];
  foreignKeys: ForeignKeySpec[];
};

export const SCHEMA_TABLES: Record<string, TableSpec> = {
  "teams": {
    "columns": {
      "id": {
        "type": "uuid",
        "notNull": true,
        "default": {
          "kind": "uuid"
        }
      },
      "name": {
        "type": "text",
        "notNull": true,
        "default": null
      },
      "slug": {
        "type": "text",
        "notNull": true,
        "default": null
      },
      "display_name": {
        "type": "text",
        "notNull": false,
        "default": null
      },
      "color": {
        "type": "text",
        "notNull": true,
        "default": null
      },
      "assigned_pillars": {
        "type": "text[]",
        "notNull": true,
        "default": {
          "kind": "literal",
          "value": []
        }
      },
      "facilitator_notes": {
        "type": "text",
        "notNull": false,
        "default": null
      },
      "creative_platform_name": {
        "type": "text",
        "notNull": false,
        "default": null
      },
      "creative_platform_brief": {
        "type": "text",
        "notNull": false,
        "default": null
      },
      "created_at": {
        "type": "timestamptz",
        "notNull": false,
        "default": {
          "kind": "now"
        }
      }
    },
    "primaryKey": [
      "id"
    ],
    "uniques": [
      {
        "name": "teams_slug_key",
        "columns": [
          "slug"
        ]
      }
    ],
    "checks": [],
    "foreignKeys": []
  },
  "ideas": {
    "columns": {
      "id": {
        "type": "uuid",
        "notNull": true,
        "default": {
          "kind": "uuid"
        }
      },
      "team_id": {
        "type": "uuid",
        "notNull": false,
        "default": null
      },
      "category": {
        "type": "text",
        "notNull": true,
        "default": null
      },
      "name": {
        "type": "text",
        "notNull": true,
        "default": null
      },
      "description": {
        "type": "text",
        "notNull": false,
        "default": null
      },
      "status": {
        "type": "text",
        "notNull": true,
        "default": {
          "kind": "literal",
          "value": "draft"
        }
      },
      "wave": {
        "type": "text",
        "notNull": false,
        "default": null
      },
      "bbei_connection": {
        "type": "text",
        "notNull": false,
        "default": null
      },
      "key_partners": {
        "type": "text",
        "notNull": false,
        "default": null
      },
      "source": {
        "type": "text",
        "notNull": true,
        "default": {
          "kind": "literal",
          "value": "team"
        }
      },
      "link_group": {
        "type": "text",
        "notNull": false,
        "default": null
      },
      "gifted_from_team_id": {
        "type": "uuid",
        "notNull": false,
        "default": null
      },
      "created_at": {
        "type": "timestamptz",
        "notNull": false,
        "default": {
          "kind": "now"
        }
      },
      "updated_at": {
        "type": "timestamptz",
        "notNull": false,
        "default": {
          "kind": "now"
        }
      },
      "presenting": {
        "type": "boolean",
        "notNull": true,
        "default": {
          "kind": "literal",
          "value": false
        }
      },
      "print_status": {
        "type": "text",
        "notNull": false,
        "default": null
      },
      "print_options": {
        "type": "text[]",
        "notNull": false,
        "default": null
      },
      "print_url": {
        "type": "text",
        "notNull": false,
        "default": null
      },
      "print_source": {
        "type": "text",
        "notNull": false,
        "default": null
      },
      "print_note": {
        "type": "text",
        "notNull": false,
        "default": null
      }
    },
    "primaryKey": [
      "id"
    ],
    "uniques": [],
    "checks": [
      {
        "name": "ideas_status_check",
        "column": "status",
        "allowed": [
          "draft",
          "coached",
          "starting_lineup",
          "bench"
        ]
      },
      {
        "name": "ideas_wave_check",
        "column": "wave",
        "allowed": [
          "wave_1",
          "wave_2"
        ]
      },
      {
        "name": "ideas_source_check",
        "column": "source",
        "allowed": [
          "team",
          "quick_toss",
          "tissue",
          "ai_scouted"
        ]
      },
      {
        "name": "ideas_print_status_check",
        "column": "print_status",
        "allowed": [
          "developing",
          "developed"
        ]
      }
    ],
    "foreignKeys": [
      {
        "name": "ideas_team_id_fkey",
        "column": "team_id",
        "refTable": "teams",
        "refColumn": "id",
        "onDelete": "no action"
      },
      {
        "name": "ideas_gifted_from_team_id_fkey",
        "column": "gifted_from_team_id",
        "refTable": "teams",
        "refColumn": "id",
        "onDelete": "no action"
      }
    ]
  },
  "votes": {
    "columns": {
      "id": {
        "type": "uuid",
        "notNull": true,
        "default": {
          "kind": "uuid"
        }
      },
      "idea_id": {
        "type": "uuid",
        "notNull": true,
        "default": null
      },
      "category": {
        "type": "text",
        "notNull": true,
        "default": null
      },
      "voter_id": {
        "type": "text",
        "notNull": true,
        "default": null
      },
      "created_at": {
        "type": "timestamptz",
        "notNull": false,
        "default": {
          "kind": "now"
        }
      }
    },
    "primaryKey": [
      "id"
    ],
    "uniques": [
      {
        "name": "votes_idea_id_voter_id_key",
        "columns": [
          "idea_id",
          "voter_id"
        ]
      }
    ],
    "checks": [],
    "foreignKeys": [
      {
        "name": "votes_idea_id_fkey",
        "column": "idea_id",
        "refTable": "ideas",
        "refColumn": "id",
        "onDelete": "cascade"
      }
    ]
  },
  "training_notes": {
    "columns": {
      "id": {
        "type": "uuid",
        "notNull": true,
        "default": {
          "kind": "uuid"
        }
      },
      "idea_id": {
        "type": "uuid",
        "notNull": false,
        "default": null
      },
      "coach_type": {
        "type": "text",
        "notNull": true,
        "default": null
      },
      "team_slug": {
        "type": "text",
        "notNull": false,
        "default": null
      },
      "user_prompt": {
        "type": "text",
        "notNull": false,
        "default": null
      },
      "ai_response": {
        "type": "text",
        "notNull": true,
        "default": null
      },
      "is_saved": {
        "type": "boolean",
        "notNull": false,
        "default": {
          "kind": "literal",
          "value": false
        }
      },
      "created_at": {
        "type": "timestamptz",
        "notNull": false,
        "default": {
          "kind": "now"
        }
      }
    },
    "primaryKey": [
      "id"
    ],
    "uniques": [],
    "checks": [],
    "foreignKeys": [
      {
        "name": "training_notes_idea_id_fkey",
        "column": "idea_id",
        "refTable": "ideas",
        "refColumn": "id",
        "onDelete": "no action"
      }
    ]
  },
  "coach_prompt_overrides": {
    "columns": {
      "coach_type": {
        "type": "text",
        "notNull": true,
        "default": null
      },
      "system_prompt": {
        "type": "text",
        "notNull": true,
        "default": null
      },
      "updated_at": {
        "type": "timestamptz",
        "notNull": false,
        "default": {
          "kind": "now"
        }
      }
    },
    "primaryKey": [
      "coach_type"
    ],
    "uniques": [],
    "checks": [],
    "foreignKeys": []
  },
  "ticker_messages": {
    "columns": {
      "id": {
        "type": "uuid",
        "notNull": true,
        "default": {
          "kind": "uuid"
        }
      },
      "message": {
        "type": "text",
        "notNull": true,
        "default": null
      },
      "style": {
        "type": "text",
        "notNull": true,
        "default": {
          "kind": "literal",
          "value": "standard"
        }
      },
      "reporter": {
        "type": "text",
        "notNull": false,
        "default": null
      },
      "is_active": {
        "type": "boolean",
        "notNull": false,
        "default": {
          "kind": "literal",
          "value": true
        }
      },
      "created_at": {
        "type": "timestamptz",
        "notNull": false,
        "default": {
          "kind": "now"
        }
      }
    },
    "primaryKey": [
      "id"
    ],
    "uniques": [],
    "checks": [
      {
        "name": "ticker_messages_style_check",
        "column": "style",
        "allowed": [
          "standard",
          "breaking"
        ]
      }
    ],
    "foreignKeys": []
  },
  "workshop_settings": {
    "columns": {
      "key": {
        "type": "text",
        "notNull": true,
        "default": null
      },
      "value": {
        "type": "text",
        "notNull": true,
        "default": null
      },
      "updated_at": {
        "type": "timestamptz",
        "notNull": false,
        "default": {
          "kind": "now"
        }
      }
    },
    "primaryKey": [
      "key"
    ],
    "uniques": [],
    "checks": [],
    "foreignKeys": []
  },
  "category_briefs": {
    "columns": {
      "category": {
        "type": "text",
        "notNull": true,
        "default": null
      },
      "brief_context": {
        "type": "text",
        "notNull": false,
        "default": null
      },
      "fan_context": {
        "type": "text",
        "notNull": false,
        "default": null
      },
      "updated_at": {
        "type": "timestamptz",
        "notNull": false,
        "default": {
          "kind": "now"
        }
      }
    },
    "primaryKey": [
      "category"
    ],
    "uniques": [],
    "checks": [],
    "foreignKeys": []
  },
  "pillar_visions": {
    "columns": {
      "category": {
        "type": "text",
        "notNull": true,
        "default": null
      },
      "vision_text": {
        "type": "text",
        "notNull": false,
        "default": null
      },
      "ai_draft": {
        "type": "text",
        "notNull": false,
        "default": null
      },
      "updated_at": {
        "type": "timestamptz",
        "notNull": false,
        "default": {
          "kind": "now"
        }
      }
    },
    "primaryKey": [
      "category"
    ],
    "uniques": [],
    "checks": [],
    "foreignKeys": []
  }
};

/** Every function the SQL declares — the shim's known-RPC set. An RPC
    outside this list fails with PGRST202 instead of silently succeeding. */
export const SCHEMA_FUNCTIONS: readonly string[] = ["cast_vote","merge_ideas"];
